name = "telegram-bot"
main = "worker.js"
compatibility_date = "2025-05-29"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_TOKEN = "7404291471:AAGlyiRxnkQ9KM-8aVkECbeIuFuWkJoSdxY"

[[kv_namespaces]]
binding = "POINTS_STORE"
id = "a3157ad25ee94e7daaa7d968811a901a"
